# Generated by Django 3.1.2 on 2022-01-24 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('translation', models.CharField(max_length=100)),
                ('to_guess', models.CharField(max_length=100)),
                ('text', models.CharField(blank=True, default='', max_length=100)),
                ('answer', models.CharField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four')], max_length=5)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
