# Generated by Django 3.1.2 on 2022-01-25 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(choices=[(0, 'Mid tone'), (1, 'Low tone'), (2, 'Falling tone'), (3, 'High tone'), (4, 'Rising tone')], max_length=5),
        ),
    ]
